name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install pyinstaller keyboard mouse
      - run: pyinstaller --onefile --windowed main.py --name BindMacro
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/BindMacro.exe
          generate_release_notes: true
